#!/usr/bin/env bash
# The script tests the IP address passed as an argument

ip_A="${1}"
fp=$(basename "${BASH_SOURCE[@]}")
if ! [ "$ip_A" ]; then
	echo "Usage: ${fp} {IP_ADDRESS}"
else
	ping -c 5 "${ip_A}"
fi
